# Generated by Django 4.0.6 on 2022-07-26 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_licencia', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)])),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=10, null=True)),
                ('modelo', models.CharField(max_length=15, null=True)),
                ('color', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
