# Generated by Django 4.0.6 on 2022-07-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='marca',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='modelo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
