# Generated by Django 4.0.6 on 2022-07-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
        ('taxistas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='licencia_id',
        ),
        migrations.AddField(
            model_name='user',
            name='licencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licencias.licencia'),
        ),
    ]
