# Generated by Django 4.0.6 on 2022-07-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxistas', '0003_alter_user_licencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
