# Generated by Django 4.0.6 on 2022-07-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxistas', '0005_alter_user_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
    ]
